# NumPy

- Alternative to python list
- Calculations over entire arrays
- Easy and Fast

In [2]:
# Creating a numpy array
import numpy as np

weight = [70, 80, 60, 90, 75]
height = [1.75, 1.80, 1.65, 1.90, 1.78]

np_weight = np.array(weight)
np_height = np.array(height)

bmi = np_weight / np_height ** 2

print(bmi)

[22.85714286 24.69135802 22.03856749 24.93074792 23.67125363]


In [ ]:
# Numpy Subsetting

# Print the second element in the bmi array
print(bmi[1])

# Print a boolean array where each element indicates if the corresponding bmi value is greater than 23
print(bmi > 23)

# Print the elements in the bmi array that are greater than 23
print(bmi[bmi > 23])

24.691358024691358
[False  True False  True  True]
[24.69135802 24.93074792 23.67125363]


## 2D Numpy Array


In [3]:
height_weight = [[70, 80, 60, 90, 75],[1.75, 1.80, 1.65, 1.90, 1.78]]
np_height_weight = np.array(height_weight)

print(np_height_weight)
print(np_height_weight[0][1])
print(np_height_weight[0,1])

print(np_height_weight[: , 1:3])

[[70.   80.   60.   90.   75.  ]
 [ 1.75  1.8   1.65  1.9   1.78]]
80.0
80.0
[[80.   60.  ]
 [ 1.8   1.65]]


In [1]:
import numpy as np

baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


## Numpy: Basic Statistics

In [2]:
import numpy as np

# Create np_height_in from np_baseball
np_height_in = np_baseball[: , 0]

# Print out the mean of np_height_in
print(np.mean(np_height_in))

# Print out the median of np_height_in
print(np.median(np_height_in))

198.25
199.0


In [3]:
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column
corr = np.corrcoef(np_baseball[:,0], np_baseball[:,1])
print("Correlation: " + str(corr))

Average: 198.25
Median: 199.0
Standard Deviation: 14.635146053251399
Correlation: [[1.         0.95865738]
 [0.95865738 1.        ]]
